/**
 * Base class for a set of bricks that form a single shader.
 * @docurl https://docs.daz3d.com/public/software/dazstudio/4/referenceguide/scripting/api_reference/object_index/brickset_dz
 */
declare class DzBrickSet extends DzRefCountedItem {

    /* Methods */

    /**
     * @returns string The absolute shader path for the generated shader.
     */
    getFullShaderPath(): string; // String

    /**
     * @returns string The destination of the shader file this set will create.
     */
    getShaderFile(): string; // String

    /**
     * Invalidates the files generated by this set.
     */
    invalidateFiles(): void;

    /**
     * Queues this brick set to be recompiled if necessary.
     */
    sendForUpdate(): void;

    /* Undocumented Augment Members */

    /** @undocumented */
    static AmbientLight: number;	// 1

    /** @undocumented */
    static Displacement: number;	// 7

    /** @undocumented */
    static DistantLight: number;	// 3

    /** @undocumented */
    static Imager: number;	// 8

    /** @undocumented */
    static Light: number;	// 2

    /** @undocumented */
    static LightArea: number;	// 3

    /** @undocumented */
    static None: number;	// 0

    /** @undocumented */
    static NullLight: number;	// 0

    /** @undocumented */
    static PointLight: number;	// 2

    /** @undocumented */
    static SpotLight: number;	// 4

    /** @undocumented */
    static Surface: number;	// 1

    /** @undocumented */
    static VolumeAtmosphere: number;	// 4

    /** @undocumented */
    static VolumeExterior: number;	// 6

    /** @undocumented */
    static VolumeInterior: number;	// 5

    /** @undocumented */
    name: string;	// shader_Volume

    /** @undocumented */
    objectName: string;	// shader_Volume

    /** @undocumented */
    allowsAutoBake(): any;

    /** @undocumented */
    className(): any;

    /** @undocumented */
    deleteLater(): any;

    /** @undocumented */
    destroyed(): void;

    /** @undocumented */
    destroyed(p0: QObject): void;

    /** @undocumented */
    getBackgroundColor(): any;

    /** @undocumented */
    getBakeSettings(): any;

    /** @undocumented */
    getBrickUserOwner(): any;

    /** @undocumented */
    getNewToken(): any;

    /** @undocumented */
    getOwner(): any;

    /** @undocumented */
    getRenderSettings(): any;

    /** @undocumented */
    getRoot(): any;

    /** @undocumented */
    getShaderType(): any;

    /** @undocumented */
    inherits(): any;

    /** @undocumented */
    isActiveInBakePass(): any;

    /** @undocumented */
    isActiveInBeautyPass(): any;

    /** @undocumented */
    isActiveInShadowPass(): any;

    /** @undocumented */
    isBakePass(): any;

    /** @undocumented */
    isBeautyPass(): any;

    /** @undocumented */
    isOnlyInShadowPass(): any;

    /** @undocumented */
    isShadowPass(): any;

    /** @undocumented */
    setColorAttrib(p0: string, p1: string, p2: QColor): any;

    /** @undocumented */
    setColorAttrib(p0: string, p1: string, p2: DzVec3): any;

    /** @undocumented */
    setColorAttrib(p0: string, p1: string, p2: number, p3: number, p4: number): any;

    /** @undocumented */
    setColorAttrib(p0: string, p1: string, p2: number, p3: number, p4: number, p5: boolean): any;

    /** @undocumented */
    setColorToken(p0: string, p1: QColor): any;

    /** @undocumented */
    setDisplacementBound(p0: number): any;

    /** @undocumented */
    setFloatAttrib(p0: string, p1: string, p2: number): any;

    /** @undocumented */
    setFloatToken(p0: string, p1: number): any;

    /** @undocumented */
    setIntegerAttrib(p0: string, p1: string, p2: number): any;

    /** @undocumented */
    setIntegerToken(p0: string, p1: number): any;

    /** @undocumented */
    setMatrixAttrib(p0: string, p1: string, p2: DzMatrix4): any;

    /** @undocumented */
    setMatrixToken(p0: string, p1: DzMatrix4): any;

    /** @undocumented */
    setNormalAttrib(p0: string, p1: string, p2: DzVec3): any;

    /** @undocumented */
    setNormalToken(p0: string, p1: DzVec3): any;

    /** @undocumented */
    setPointAttrib(p0: string, p1: string, p2: DzVec3): any;

    /** @undocumented */
    setPointToken(p0: string, p1: DzVec3): any;

    /** @undocumented */
    setStringAttrib(p0: string, p1: string, p2: string): any;

    /** @undocumented */
    setStringToken(p0: string, p1: string): any;

    /** @undocumented */
    setVectorAttrib(p0: string, p1: string, p2: DzVec3): any;

    /** @undocumented */
    setVectorToken(p0: string, p1: DzVec3): any;
}
