declare class DzHeadLight {

    /* Properties */
    objectName: string;
    name: string;
    elementID: number;
    renderPriority: number;
    assetIdAliases: QObject;
    nameAliases: QObject;
    assetId: string;
    frameWidth: number;
    focalDistance: number;
    focalLength: number;
    type: number;
    nearClippingPlane: number;
    farClippingPlane: number;
    useLocalDimensions: boolean;
    pixelsWidth: number;
    pixelsHeight: number;
    aspectWidth: number;
    aspectHeight: number;
    aspectRatio: number;
    proportionsConstrained: boolean;
    headlightMode: any;
    headlightOffset: QObject;
    None: number;
    DeepShadowMap: number;
    Raytraced: number;
    FRONT_CAMERA: number;
    BACK_CAMERA: number;
    LEFT_CAMERA: number;
    RIGHT_CAMERA: number;
    TOP_CAMERA: number;
    BOTTOM_CAMERA: number;
    PERSPECTIVE_CAMERA: number;
    ORTHO_CAMERA: number;
    GENERAL_CAMERA: number;
    LOCAL_PIXEL_WIDTH: number;
    LOCAL_PIXEL_HEIGHT: number;
    LOCAL_ASPECT_WIDTH: number;
    LOCAL_ASPECT_HEIGHT: number;

    /* Methods */
    destroyed(): any; // TODO ;
    destroyed(): any; // TODO ;
    deleteLater(): any; // TODO ;
    nameChanged(): any; // TODO ;
    className(): any; // TODO ;
    makePersistent(): any; // TODO ;
    inherits(): any; // TODO ;
    iskindof(): any; // TODO ;
    getName(): any; // TODO ;
    propertyAdded(): any; // TODO ;
    propertyRemoved(): any; // TODO ;
    propertyListChanged(): any; // TODO ;
    propertyListInTreeChanged(): any; // TODO ;
    propertyTreeChanged(): any; // TODO ;
    privatePropertyAdded(): any; // TODO ;
    privatePropertyRemoved(): any; // TODO ;
    privatePropertyListChanged(): any; // TODO ;
    privatePropertyListInTreeChanged(): any; // TODO ;
    privatePropertyTreeChanged(): any; // TODO ;
    labelChanged(): any; // TODO ;
    parentChanged(): any; // TODO ;
    mergeElementSignal(): any; // TODO ;
    duplicateElementSignal(): any; // TODO ;
    createElementCopySignal(): any; // TODO ;
    setAttributes(): any; // TODO ;
    setName(): any; // TODO ;
    setLabel(): any; // TODO ;
    update(): any; // TODO ;
    clearAnimData(): any; // TODO ;
    clearAllAnimData(): any; // TODO ;
    addProperty(): any; // TODO ;
    insertProperty(): any; // TODO ;
    removeProperty(): any; // TODO ;
    removeProperty(): any; // TODO ;
    moveProperty(): any; // TODO ;
    addPrivateProperty(): any; // TODO ;
    insertPrivateProperty(): any; // TODO ;
    removePrivateProperty(): any; // TODO ;
    removePrivateProperty(): any; // TODO ;
    movePrivateProperty(): any; // TODO ;
    addDataItem(): any; // TODO ;
    removeDataItem(): any; // TODO ;
    deleteDataItem(): any; // TODO ;
    copyFrom(): any; // TODO ;
    setLoadScript(): any; // TODO ;
    beginEdit(): any; // TODO ;
    finishEdit(): any; // TODO ;
    cancelEdit(): any; // TODO ;
    shouldSortOnLoad(): any; // TODO ;
    getLabel(): any; // TODO ;
    getAttributes(): any; // TODO ;
    getNumProperties(): any; // TODO ;
    getProperty(): any; // TODO ;
    getPropertyList(): any; // TODO ;
    isPropertyNameUnique(): any; // TODO ;
    isPropertyNameUnique(): any; // TODO ;
    findProperty(): any; // TODO ;
    findProperty(): any; // TODO ;
    findPropertyByLabel(): any; // TODO ;
    findPropertyByLabel(): any; // TODO ;
    getPropertyGroups(): any; // TODO ;
    findMatchingProperty(): any; // TODO ;
    getNumPrivateProperties(): any; // TODO ;
    getPrivateProperty(): any; // TODO ;
    getPrivatePropertyList(): any; // TODO ;
    isPrivatePropertyNameUnique(): any; // TODO ;
    isPrivatePropertyNameUnique(): any; // TODO ;
    findPrivateProperty(): any; // TODO ;
    findPrivateProperty(): any; // TODO ;
    findPrivatePropertyByLabel(): any; // TODO ;
    findPrivatePropertyByLabel(): any; // TODO ;
    getPrivatePropertyGroups(): any; // TODO ;
    getNumDataItems(): any; // TODO ;
    getDataItem(): any; // TODO ;
    getDataItemList(): any; // TODO ;
    isDataItemNameUnique(): any; // TODO ;
    isDataItemNameUnique(): any; // TODO ;
    findDataItem(): any; // TODO ;
    getLoadScript(): any; // TODO ;
    copyToClipboard(): any; // TODO ;
    copyToClipboard(): any; // TODO ;
    getNumElementChildren(): any; // TODO ;
    getElementChild(): any; // TODO ;
    getElementParent(): any; // TODO ;
    inEdit(): any; // TODO ;
    moveDataItemToIndex(): any; // TODO ;
    findDataItemIndex(): any; // TODO ;
    duplicateMissingCustomData(): any; // TODO ;
    duplicateMissingProperties(): any; // TODO ;
    duplicateMissingPrivateProperties(): any; // TODO ;
    duplicateMissingCustomDataWithContext(): any; // TODO ;
    duplicateMissingPropertiesWithContext(): any; // TODO ;
    duplicateMissingPrivatePropertiesWithContext(): any; // TODO ;
    doMergeElement(): any; // TODO ;
    doDuplicateElement(): any; // TODO ;
    mergeElement(): any; // TODO ;
    duplicateElement(): any; // TODO ;
    createElementCopy(): any; // TODO ;
    parentChanged(): any; // TODO ;
    transformChanged(): any; // TODO ;
    selected(): any; // TODO ;
    rotationOrderChanged(): any; // TODO ;
    childAdded(): any; // TODO ;
    childRemoved(): any; // TODO ;
    childListChanged(): any; // TODO ;
    objectChanged(): any; // TODO ;
    drawnDataChanged(): any; // TODO ;
    visibilityChanged(): any; // TODO ;
    selectabilityChanged(): any; // TODO ;
    aboutToBeRemoved(): any; // TODO ;
    removed(): any; // TODO ;
    added(): any; // TODO ;
    hiddenChanged(): any; // TODO ;
    riggingChanged(): any; // TODO ;
    materialListChanged(): any; // TODO ;
    materialSelectionChanged(): any; // TODO ;
    uvsChanged(): any; // TODO ;
    assetModified(): any; // TODO ;
    assetWasSaved(): any; // TODO ;
    boundBoxInvalidated(): any; // TODO ;
    aboutToDelete(): any; // TODO ;
    inheritScaleChanged(): any; // TODO ;
    materialSelectionSetsChanged(): any; // TODO ;
    childListOrderChanged(): any; // TODO ;
    promoteSelectionChanged(): any; // TODO ;
    topologyChanged(): any; // TODO ;
    objectDuplicateAndSetSignal(): any; // TODO ;
    modifierDuplicateFinished(): any; // TODO ;
    setManipOverColor(): any; // TODO ;
    clearManipOverColor(): any; // TODO ;
    update(): any; // TODO ;
    finalize(): any; // TODO ;
    finalize(): any; // TODO ;
    finalize(): any; // TODO ;
    select(): any; // TODO ;
    select(): any; // TODO ;
    setSelectable(): any; // TODO ;
    setVisible(): any; // TODO ;
    setRotationOrder(): any; // TODO ;
    setObject(): any; // TODO ;
    addNodeChild(): any; // TODO ;
    addNodeChild(): any; // TODO ;
    removeNodeChild(): any; // TODO ;
    removeNodeChild(): any; // TODO ;
    removeAllNodeChildren(): any; // TODO ;
    moveNodeChildToIndex(): any; // TODO ;
    moveNodeChildToIndex(): any; // TODO ;
    findChildIndex(): any; // TODO ;
    setWSTransform(): any; // TODO ;
    setWSTransform(): any; // TODO ;
    setWSPos(): any; // TODO ;
    setWSPos(): any; // TODO ;
    setWSRot(): any; // TODO ;
    setWSRot(): any; // TODO ;
    setWSScale(): any; // TODO ;
    setWSScale(): any; // TODO ;
    setLocalTransform(): any; // TODO ;
    setLocalTransform(): any; // TODO ;
    setLocalTransform(): any; // TODO ;
    setLocalTransform(): any; // TODO ;
    setToolLocalTransform(): any; // TODO ;
    setToolLocalTransform(): any; // TODO ;
    setLocalPos(): any; // TODO ;
    setLocalPos(): any; // TODO ;
    setLocalRot(): any; // TODO ;
    setLocalRot(): any; // TODO ;
    setToolLocalRot(): any; // TODO ;
    setToolLocalRot(): any; // TODO ;
    setLocalScale(): any; // TODO ;
    setLocalScale(): any; // TODO ;
    setLocalScale(): any; // TODO ;
    setLocalScale(): any; // TODO ;
    setOrientation(): any; // TODO ;
    setOrientation(): any; // TODO ;
    setOrientationAngles(): any; // TODO ;
    setOrientationAngles(): any; // TODO ;
    setOrigin(): any; // TODO ;
    setOrigin(): any; // TODO ;
    setEndPoint(): any; // TODO ;
    setEndPoint(): any; // TODO ;
    adjustOrientation(): any; // TODO ;
    adjustOrientationAngles(): any; // TODO ;
    adjustOrigin(): any; // TODO ;
    adjustEndPoint(): any; // TODO ;
    clearTransformData(): any; // TODO ;
    clearAllTransformData(): any; // TODO ;
    setInheritScale(): any; // TODO ;
    setPointAtTarget(): any; // TODO ;
    setPointAtStrength(): any; // TODO ;
    setHidden(): any; // TODO ;
    setPromoteSelection(): any; // TODO ;
    setRenderPriority(): any; // TODO ;
    setRenderPriority(): any; // TODO ;
    setVisibleInRender(): any; // TODO ;
    setSelectionMap(): any; // TODO ;
    setPresentation(): any; // TODO ;
    setPreviewBox(): any; // TODO ;
    modifyAsset(): any; // TODO ;
    modifyAsset(): any; // TODO ;
    invalidateBoundingBoxes(): any; // TODO ;
    invalidateBoundingBoxes(): any; // TODO ;
    getSkeleton(): any; // TODO ;
    getRotationOrder(): any; // TODO ;
    isSelected(): any; // TODO ;
    isSelectable(): any; // TODO ;
    isVisible(): any; // TODO ;
    isVisibileInRender(): any; // TODO ;
    castsShadow(): any; // TODO ;
    getObject(): any; // TODO ;
    getNumNodeChildren(): any; // TODO ;
    getNodeChild(): any; // TODO ;
    getNodeChildren(): any; // TODO ;
    getNodeChildren(): any; // TODO ;
    isNodeChild(): any; // TODO ;
    findNodeChild(): any; // TODO ;
    findNodeChild(): any; // TODO ;
    findNodeChildByAssetID(): any; // TODO ;
    findNodeChildByAssetID(): any; // TODO ;
    findNodeChildByAssetID(): any; // TODO ;
    findNodeChildByNameOrAlias(): any; // TODO ;
    findNodeChildByNameOrAlias(): any; // TODO ;
    getNodeParent(): any; // TODO ;
    isRootNode(): any; // TODO ;
    getLocalBoundingBox(): any; // TODO ;
    getLocalOrientedBox(): any; // TODO ;
    getWSBoundingBox(): any; // TODO ;
    getWSOrientedBox(): any; // TODO ;
    getPreviewBox(): any; // TODO ;
    getWSTransform(): any; // TODO ;
    getWSTransform(): any; // TODO ;
    getWSTransform(): any; // TODO ;
    getToolWSTransform(): any; // TODO ;
    getToolWSTransform(): any; // TODO ;
    getWSPos(): any; // TODO ;
    getWSPos(): any; // TODO ;
    getWSPos(): any; // TODO ;
    getWSRot(): any; // TODO ;
    getWSRot(): any; // TODO ;
    getWSRot(): any; // TODO ;
    getToolWSRot(): any; // TODO ;
    getToolWSRot(): any; // TODO ;
    getWSScale(): any; // TODO ;
    getWSScale(): any; // TODO ;
    getWSScale(): any; // TODO ;
    getLocalTransform(): any; // TODO ;
    getLocalTransform(): any; // TODO ;
    getLocalTransform(): any; // TODO ;
    getLocalPos(): any; // TODO ;
    getLocalPos(): any; // TODO ;
    getLocalPos(): any; // TODO ;
    getLocalRot(): any; // TODO ;
    getLocalRot(): any; // TODO ;
    getLocalRot(): any; // TODO ;
    getToolLocalRot(): any; // TODO ;
    getToolLocalRot(): any; // TODO ;
    getLocalScale(): any; // TODO ;
    getLocalScale(): any; // TODO ;
    getLocalScale(): any; // TODO ;
    getOrientation(): any; // TODO ;
    getOrientation(): any; // TODO ;
    updateOrientation(): any; // TODO ;
    getOrigin(): any; // TODO ;
    getOrigin(): any; // TODO ;
    getEndPoint(): any; // TODO ;
    getEndPoint(): any; // TODO ;
    getSelectionMap(): any; // TODO ;
    getXPosControl(): any; // TODO ;
    getYPosControl(): any; // TODO ;
    getZPosControl(): any; // TODO ;
    getXRotControl(): any; // TODO ;
    getYRotControl(): any; // TODO ;
    getZRotControl(): any; // TODO ;
    getScaleControl(): any; // TODO ;
    getXScaleControl(): any; // TODO ;
    getYScaleControl(): any; // TODO ;
    getZScaleControl(): any; // TODO ;
    getSelectabilityControl(): any; // TODO ;
    getVisibilityControl(): any; // TODO ;
    getRenderVisibilityControl(): any; // TODO ;
    getShadowControl(): any; // TODO ;
    getRenderPriorityControl(): any; // TODO ;
    getPointAtControl(): any; // TODO ;
    getOriginXControl(): any; // TODO ;
    getOriginYControl(): any; // TODO ;
    getOriginZControl(): any; // TODO ;
    getEndXControl(): any; // TODO ;
    getEndYControl(): any; // TODO ;
    getEndZControl(): any; // TODO ;
    getOrientXControl(): any; // TODO ;
    getOrientYControl(): any; // TODO ;
    getOrientZControl(): any; // TODO ;
    inheritsScale(): any; // TODO ;
    isHidden(): any; // TODO ;
    isInScene(): any; // TODO ;
    isSelectionPromoted(): any; // TODO ;
    getRenderPriority(): any; // TODO ;
    getPresentation(): any; // TODO ;
    getSelectionNode(): any; // TODO ;
    isBoneSelectingNode(): any; // TODO ;
    setInvisibleByGroup(): any; // TODO ;
    setUnselectableByGroup(): any; // TODO ;
    invisibleByGroup(): any; // TODO ;
    unselectableByGroup(): any; // TODO ;
    getWeightMapHandler(): any; // TODO ;
    doObjectDuplicateAndSet(): any; // TODO ;
    isEditorNode(): any; // TODO ;
    getToolXRotControl(): any; // TODO ;
    getToolYRotControl(): any; // TODO ;
    getToolZRotControl(): any; // TODO ;
    invalidateCache(): any; // TODO ;
    selectionMapModified(): any; // TODO ;
    updateTransform(): any; // TODO ;
    updateVis(): any; // TODO ;
    updateRenderable(): any; // TODO ;
    invalidateOrientation(): any; // TODO ;
    objectDuplicateAndSet(): any; // TODO ;
    handleRendererModeChanged(): any; // TODO ;
    projectionChanged(): any; // TODO ;
    focalDistanceChanged(): any; // TODO ;
    focalLengthChanged(): any; // TODO ;
    pixelDimensionsChanged(): any; // TODO ;
    aspectRatioChanged(): any; // TODO ;
    dimensionsChanged(): any; // TODO ;
    useLocalDimensionsChanged(): any; // TODO ;
    pixelsWidthChanged(): any; // TODO ;
    pixelsHeightChanged(): any; // TODO ;
    aspectWidthChanged(): any; // TODO ;
    aspectHeightChanged(): any; // TODO ;
    proportionsConstrainedChanged(): any; // TODO ;
    frameWidthChanged(): any; // TODO ;
    headlightModeChanged(): any; // TODO ;
    headlightOffsetChanged(): any; // TODO ;
    reset(): any; // TODO ;
    aimAt(): any; // TODO ;
    frame(): any; // TODO ;
    getHeadlight(): any; // TODO ;
    getFocalPoint(): any; // TODO ;
    getFieldOfView(): any; // TODO ;
    isViewCamera(): any; // TODO ;
    updateDimensions(): any; // TODO ;
    shouldDoHeadLight(): any; // TODO ;
    categoriesChanged(): any; // TODO ;
    isDirectional(): any; // TODO ;
    getWSDirection(): any; // TODO ;
    isAreaLight(): any; // TODO ;
    getDiffuseColor(): any; // TODO ;
    isOn(): any; // TODO ;
    getCategories(): any; // TODO ;
    getCategoriesControl(): any; // TODO ;
    getShadowType(): any; // TODO ;
    getShadowTypeControl(): any; // TODO ;
    getNearClippingPlane(): any; // TODO ;
    getFarClippingPlane(): any; // TODO ;
    getIntensity(): any; // TODO ;
    getIntensityScale(): any; // TODO ;
    getFlux(): any; // TODO ;
    getLightTempature(): any; // TODO ;
    getLightWidth(): any; // TODO ;
    getLightHeight(): any; // TODO ;
    getLightTwoSided(): any; // TODO ;
    photometricMode(): any; // TODO ;
    getLightGeometry(): any; // TODO ;
    renderEmitter(): any; // TODO ;
    getShadowColorControl(): any; // TODO ;
    getShadowIntensityControl(): any; // TODO ;
    getShadowBiasControl(): any; // TODO ;
    getShadowSoftnessControl(): any; // TODO ;
    getIlluminationControl(): any; // TODO ;
    getDiffuseColorControl(): any; // TODO ;
    getIntensityControl(): any; // TODO ;
    getIntensityScaleControl(): any; // TODO ;
    getLightGeometryControl(): any; // TODO ;
    getLightHeightControl(): any; // TODO ;
    getLightWidthControl(): any; // TODO ;
    getLightTwoSidedControl(): any; // TODO ;
    getPhotometricModeControl(): any; // TODO ;
    getRenderEmitterControl(): any; // TODO ;
    getLightFluxControl(): any; // TODO ;
    getLightTemperatureControl(): any; // TODO ;
    handlePhotometricModeChanged(): any; // TODO ;
    getCamera(): any; // TODO ;
    inherits(): any; // TODO ;
    className(): any; // TODO ;
}