declare class DzTextureConvertorOptions {

    /* Properties */
    objectName: string;
    renderImgToId: number;
    renderMovToId: number;
    renderImgFilename: string;
    renderMovFilename: string;
    renderSerFilename: string;
    lastRenderImgFilename: string;
    lastRenderMovFilename: string;
    lastRenderSerFilename: string;
    renderViewport: boolean;
    isAspectConstrained: boolean;
    aspect: number;
    aspectWidth: number;
    aspectHeight: number;
    imageSize: QObject;
    renderType: number;
    renderStyle: number;
    rayTraceDepth: number;
    openGLPasses: number;
    useGLSL: boolean;
    isCurrentFrameRender: boolean;
    getStartTime: QObject;
    startTime: QObject;
    getEndTime: QObject;
    endTime: QObject;
    useMotionBlur: boolean;
    motionBlurPct: number;
    motionBlurSamples: number;
    motionBlurOffset: number;
    xPixelSamples: number;
    yPixelSamples: number;
    shadowSamples: number;
    shadingRate: number;
    doubleSided: boolean;
    gain: number;
    gamma: number;
    pixelFilter: number;
    xFilterWidth: number;
    yFilterWidth: number;
    showPreview: boolean;
    gammaCorrection: number;
    convertImgPath: string;
    imageType: string;
    presetId: number;
    hardwareCutOffSize: number;
    forceResize: boolean;
    ScreenShot: number;
    HardwareAssisted: number;
    Software: number;
    ActiveView: number;
    NewWindow: number;
    DirectToFile: number;
    MovieFile: number;
    ImageSeries: number;
    Normal: number;
    Cartoon: number;
    Box: number;
    Triangle: number;
    CatmullRom: number;
    Gaussian: number;
    Sinc: number;
    GCOff: number;
    GCOn: number;
    name: string;

    /* Methods */
    destroyed(): any; // TODO ;
    destroyed(): any; // TODO ;
    deleteLater(): any; // TODO ;
    aspectChanged(): any; // TODO ;
    aspectChanged(): any; // TODO ;
    renderImgTargetChanged(): any; // TODO ;
    renderMovTargetChanged(): any; // TODO ;
    renderImgFilenameChanged(): any; // TODO ;
    renderMovFilenameChanged(): any; // TODO ;
    renderSerFilenameChanged(): any; // TODO ;
    renderViewportChanged(): any; // TODO ;
    aspectConstrainChanged(): any; // TODO ;
    imageSizeChanged(): any; // TODO ;
    renderTypeChanged(): any; // TODO ;
    renderStyleChanged(): any; // TODO ;
    rayTraceDepthChanged(): any; // TODO ;
    openGLPassesChanged(): any; // TODO ;
    useGLSLChanged(): any; // TODO ;
    renderCurrentFrameChanged(): any; // TODO ;
    startTimeChanged(): any; // TODO ;
    endTimeChanged(): any; // TODO ;
    useMotionBlurChanged(): any; // TODO ;
    motionBlurPctChanged(): any; // TODO ;
    motionBlurOffsetChanged(): any; // TODO ;
    motionBlurSamplesChanged(): any; // TODO ;
    xPixelSamplesChanged(): any; // TODO ;
    yPixelSamplesChanged(): any; // TODO ;
    shadowSamplesChanged(): any; // TODO ;
    shadingRateChanged(): any; // TODO ;
    doubleSidedChanged(): any; // TODO ;
    gainChanged(): any; // TODO ;
    gammaChanged(): any; // TODO ;
    pixelFilterChanged(): any; // TODO ;
    gammaCorrectionChanged(): any; // TODO ;
    xFilterWidthChanged(): any; // TODO ;
    yFilterWidthChanged(): any; // TODO ;
    showPreviewChanged(): any; // TODO ;
    settingsChanged(): any; // TODO ;
    defaultsRestored(): any; // TODO ;
    setAspectRatio(): any; // TODO ;
    applyChanges(): any; // TODO ;
    resetOptions(): any; // TODO ;
    restoreDefaultSettings(): any; // TODO ;
    setToDefaults(): any; // TODO ;
    gammaCorrectColor(): any; // TODO ;
    imageTypeChanged(): any; // TODO ;
    inherits(): any; // TODO ;
    className(): any; // TODO ;
}