declare class Q3ListBox extends Q3ScrollView {

    /* Properties */
    modal: boolean;
    windowModality: number;
    geometry: QObject;
    frameGeometry: QObject;
    normalGeometry: QObject;
    pos: QObject;
    frameSize: QObject;
    size: QObject;
    rect: QObject;
    childrenRect: QObject;
    childrenRegion: QObject;
    sizePolicy: QObject;
    minimumSize: QObject;
    maximumSize: QObject;
    minimumWidth: number;
    minimumHeight: number;
    maximumWidth: number;
    maximumHeight: number;
    sizeIncrement: QObject;
    baseSize: QObject;
    cursor: QObject;
    mouseTracking: boolean;
    isActiveWindow: boolean;
    focusPolicy: number;
    focus: boolean;
    contextMenuPolicy: number;
    updatesEnabled: boolean;
    visible: boolean;
    minimized: boolean;
    maximized: boolean;
    fullScreen: boolean;
    //sizeHint: QObject;
    //
    acceptDrops: boolean;
    windowTitle: string;
    windowIcon: QObject;
    windowIconText: string;
    windowOpacity: number;
    windowModified: boolean;
    accessibleName: string;
    accessibleDescription: string;
    layoutDirection: number;
    autoFillBackground: boolean;
    styleSheet: string;
    locale: QObject;
    windowFilePath: string;
    inputMethodHints: number;
    //frameShape: number;
    //frameShadow: number;
    //lineWidth: number;
    //midLineWidth: number;
    //frameWidth: number;
    //frameRect: QObject;
    margin: number;
    //contentsRect: QObject;
    //resizePolicy: number;
    //vScrollBarMode: number;
    //hScrollBarMode: number;
    //visibleWidth: number;
    //visibleHeight: number;
    //contentsWidth: number;
    //contentsHeight: number;
    //contentsX: number;
    //contentsY: number;
    //dragAutoScroll: boolean;
    count: number;
    numItemsVisible: number;
    currentItem: number;
    currentText: string;
    topItem: number;
    selectionMode: number;
    multiSelection: boolean;
    columnMode: number;
    rowMode: number;
    numColumns: number;
    numRows: number;
    variableWidth: boolean;
    variableHeight: boolean;

    /* Methods */
    highlighted(obj: Q3ListBoxItem): void;
    highlighted(obj: QString): void;
    highlighted(index: number): void;
    selected(obj: Q3ListBoxItem): void;
    selected(obj: QString): void;
    selected(index: number): void;
    highlighted(obj: Q3ListBoxItem): void;
    highlighted(obj: QString): void;
    highlighted(index: number): void;
    selected(obj: Q3ListBoxItem): void;
    selected(obj: QString): void;
    selected(index: number): void;
    highlighted(obj: Q3ListBoxItem): void;
    highlighted(obj: QString): void;
    highlighted(index: number): void;
    selected(obj: Q3ListBoxItem): void;
    selected(obj: QString): void;
    selected(index: number): void;
    selectionChanged(): void;
    selectionChanged(obj: Q3ListBoxItem): void;
    selectionChanged(): void;
    selectionChanged(obj: Q3ListBoxItem): void;
    currentChanged(obj: Q3ListBoxItem): void;
    clicked(obj: Q3ListBoxItem, point?: QPoint): void;
    pressed(obj: Q3ListBoxItem, point?: QPoint): void;
    doubleClicked(obj: Q3ListBoxItem): void;
    returnPressed(obj: Q3ListBoxItem): void;
    rightButtonClicked(obj: Q3ListBoxItem, point: QPoint): void;
    rightButtonPressed(obj: Q3ListBoxItem, point: QPoint): void;
    mouseButtonPressed(obj: number, item: Q3ListBoxItem, point: QPoint): void;
    mouseButtonClicked(obj: number, item: Q3ListBoxItem, point: QPoint): void;
    contextMenuRequested(item: Q3ListBoxItem, point: QPoint): void;
    onItem(item: Q3ListBoxItem): void;
    onViewport(): void;
    clear(): void;
    ensureCurrentVisible(): void;
    clearSelection(): void;
    selectAll(select: boolean): void;
    invertSelection(): void;
    clearInputString(): void;
}